name: CI
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  test:
    name: test ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2022, ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
      # System set-up
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: lukka/get-cmake@latest
      
      - uses: ilammy/msvc-dev-cmd@v1
        if: startsWith(matrix.os, 'windows')
        
      - name: Install GCC 13 and build-essential 
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-13 g++-13 build-essential ninja-build
          echo "CC=gcc-13" >> $GITHUB_ENV
          echo "CXX=g++-13" >> $GITHUB_ENV

      # Main cppfront library
      - name: Configure cppfront
        run: cmake -G Ninja -S . -B build/cppfront -DCMAKE_BUILD_TYPE=Release
      - name: Build cppfront
        run: cmake --build build/cppfront --config Release
      - name: Install cppfront locally
        run: cmake --install build/cppfront --config Release --prefix _local

      # Regression tests
      - name: Configure regression tests
        run: >
          cmake -G Ninja -S regression-tests -B build/regression-tests -DCMAKE_BUILD_TYPE=Release 
          "-DCMAKE_PREFIX_PATH=${{github.workspace}}/_local"
      - name: Build regression tests
        run: cmake --build build/regression-tests --config Release
      - name: Run regression tests
        run: ctest --output-on-failure -C Release -j 2
        working-directory: build/regression-tests

      # Example
      - name: Configure example
        run: >
          cmake -G Ninja -S example -B build/example -DCMAKE_BUILD_TYPE=Release
          "-DCMAKE_PREFIX_PATH=${{github.workspace}}/_local"
      - name: Build example
        run: cmake --build build/example --config Release
      - name: Run example
        run: ./build/example/main && cmake -E cat xyzzy
